### ISSUE TITLE
how do I change the header color?

### ISSUE THREAD

**Issue by gesuvs** [cscan/vue-excel-editor#18]
I tried with the "init-style" property, but I was not successful in the implementation

```
 <vue-excel-column
        field="user"
        text-align="right"
        label="User"
        init-style="style"
      />
```

```
  style: {
    backgroundColor: "#42b983"
  },
```

**Comment by cscan** [comment]
something like this in your Vue file?
```css
<style>
.vue-excel-editor thead th {
  background-color: yellow !important;
}
</style>
```
